{% set data = load_setup_py_data() %}

package:
  name: slcpy
  version: {{ data['version'] }}


source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    -python
    -setuptools==52.0.0
    -click==8.0.1
    -scikit-image==0.18.1
    -numpy==1.21.0
    -tifffile==2021.7.2
    -tqdm==4.61.1
    -imagecodecs==2021.6.8

  run:
    -python
    -setuptools==52.0.0
    -click==8.0.1
    -scikit-image==0.18.1
    -numpy==1.21.0
    -tifffile==2021.7.2
    -tqdm==4.61.1
    -imagecodecs==2021.6.8

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
summary: {{ data['description'] }}

